### ISSUE TITLE
SQL Operational Error

### ISSUE THREAD

**Issue by ashleyrshipp** [matthewdean/zoom-cli#1]
Hi!!

I was looking for a workaround to change my background automatically and found your code... amazing work (and python is awesome!).

It works perfect to start, stop, and restart zoom, but as I was trying to get it to run anything with the backgrounds, I kept running into this error:

**C:\Users\ashle\Downloads\zoom-cli-master\zoom-cli-master>zoom.py background list
Traceback (most recent call last):
  File "C:\Users\ashle\Downloads\zoom-cli-master\zoom-cli-master\zoom.py", line 50, in <module>
    backgrounds = z.get_backgrounds()
  File "C:\Users\ashle\Downloads\zoom-cli-master\zoom-cli-master\lib\zoomconfig.py", line 174, in get_backgrounds
    for row in c.execute('SELECT path, name, type, customIndex, thumbPath FROM zoom_conf_video_background_a WHERE type in (?,?)', ZoomConfig.background_types_custom):
sqlite3.OperationalError: no such table: zoom_conf_video_background_a**

Any ideas on what's going on here?  I'm not very knowledgeable on SQL files.  I did notice that the "zoomus" database file is encoded "zoomus.enc.db".  Do you think this was a security patch or am I missing something??

Thanks in advance!

**Comment by matthewdean** [comment]
Hi spiderwine,

It appears that Zoom now encrypts its SQLite database at rest which broke this functionality. I am investigating how to decrypt it.
