### ISSUE TITLE
Usage clarification

### ISSUE THREAD

**Issue by elderbas** [matthewdean/zoom-cli#2]
Either I'm not running this correctly or I didn't install this correctly.

When I run `python3 zoom.py --help` I get the following

```
python3 zoom.py --help
usage: 
  zoom background get             print the current background name
  zoom background set <file>      change the virtual background
  zoom background unset           disable the virtual background

  zoom background import <path>   add virtual background(s) from a given file or directory
  zoom background export <dir>    copy virtual backgrounds to a given directory
  zoom background list            enumerate virtual backgrounds
  zoom background deleteall       delete all custom virtual backgrounds

  zoom app start                  launch zoom app if not running
  zoom app stop                   terminate zoom app if running
  zoom app restart                terminate zoom app if running and then relaunch

optional arguments:
  -h, --help  show this help message and exit
```

which seems all in order.

But anything I'm doing to execute what is in 'usage' doesn't seem to work
```
python3 zoom.py background get
Traceback (most recent call last):
  File "/Users/bschermerhorn/Code/packages/zoom-cli/zoom.py", line 42, in <module>
    print("current background: " + z.get_background())
  File "/Users/bschermerhorn/Code/packages/zoom-cli/lib/zoomconfig.py", line 35, in get_background
    return self.get_current_background_path()
  File "/Users/bschermerhorn/Code/packages/zoom-cli/lib/zoomconfig.py", line 108, in get_current_background_path
    c.execute('SELECT value FROM zoom_kv WHERE key=?', (ZoomConfig.background_path_key,))
sqlite3.OperationalError: no such table: zoom_kv
```

also

```
python3 zoom.py zoom background get
usage: 
  zoom background get             print the current background name
  zoom background set <file>      change the virtual background
  zoom background unset           disable the virtual background

  zoom background import <path>   add virtual background(s) from a given file or directory
  zoom background export <dir>    copy virtual backgrounds to a given directory
  zoom background list            enumerate virtual backgrounds
  zoom background deleteall       delete all custom virtual backgrounds

  zoom app start                  launch zoom app if not running
  zoom app stop                   terminate zoom app if running
  zoom app restart                terminate zoom app if running and then relaunch
zoom: error: argument category: invalid choice: 'zoom' (choose from 'background', 'app')
```

**Comment by elderbas** [comment]
Although looking at the other sql issue, perhaps my issue is a duplicate

https://github.com/matthewdean/zoom-cli/issues/1

**Comment by tvincent-splunk** [comment]
Anyone make any progress on this?  I have the same issue...  :-(
